#!/bin/bash

#======================================================================#
#    __     ___  __      __   __   __   ___  __
#   |__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#   |    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#   my info script
#======================================================================#


#======================================================================#
# Colors
#======================================================================#
RED='\033[0;31m'
NC='\033[0m' # No Color
#======================================================================#


#======================================================================#
# Fetch info
#======================================================================#
User="$USER@$(hostname)"
OS="$(cat /etc/os-release | grep PRETTY_NAME | sed 's/PRETTY_NAME=//' | sed 's/"//g')"
Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Pack_dpkg="$(dpkg -l | grep -c ^ii)"
# Pack_flat="$(flatpak list | grep -c system)"
CPU="$(lscpu | grep Model\ name | sed 's/Model name://' | sed 's/^[ \t]*//')"
GPU="$(glxinfo -B | grep Device: | sed 's/Device://' | sed 's/^[ \t]*//')"
Disk="$(df -h / | awk '/^\// {print $3 "/" $2 " (" $5 ")"}')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
lIP="$(hostname -I | awk '{print $1}')"
#pIP="$(curl -s http://ipecho.net/plain)"
#======================================================================#


#======================================================================#
# Display info
#======================================================================#
echo -e '          _,pier$$$$gg.        ' "${RED}  [User] ${NC}$User"
echo -e '       ,g$$$$$$$$$$$$$$$P.     ' "${RED}[Uptime] ${NC}$Uptime"
echo -e '     ,g$$P""       """Y$$.".   '
echo -e '    ,$$P"              `$$$."  ' "${RED}    [OS] ${NC}$OS"
echo -e '   ,$$P       ,ggs.     `$$b:  ' "${RED}[Kernel] ${NC}$Kernel"
echo -e '  `d$$"     ,$P""   .    $$$   ' "${RED}   [Pkg] ${NC}$Pack_dpkg (dpkg)" #, $Pack_flat (flatpak)
echo -e '   $$P      d$"     ,    $$P   ' "${RED}    [DE] ${NC}$Desktop"
echo -e '   $$:      $$.   -    ,d$$"   '
echo -e '   $$\;      Y$b._   _,d$P     ' "${RED}  [Disk] ${NC}$Disk"
echo -e '   Y$$.    `.`"Y$$$$P""        ' "${RED}   [CPU] ${NC}$CPU"
echo -e '   `$$b      "-.__             ' "${RED}   [MEM] ${NC}$RAM"
echo -e '    `Y$$                       ' "${RED}   [GPU] ${NC}$GPU"
echo -e '     `Y$$.                     ' "${RED}    [IP] ${NC}$lIP" #, $pIP
echo -e '       `$$b.                   '
echo -e '         `Y$$b.                '
echo -e '            `"Y$b._            '
echo -e '                `""""          '
#======================================================================#
