#!/bin/bash

User="$USER@$(hostname)"
OS="$(lsb_release -sirc)"
Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Pack_dpkg="$(dpkg -l | grep -c ^ii)"
Pack_flat="$(flatpak list | grep -c system)"
CPU="$(lscpu | grep Model\ name | sed 's/Model name://' | sed 's/^[ \t]*//')"
GPU="$(glxinfo -B | grep Device: | sed 's/Device://' | sed 's/^[ \t]*//')"
Disk="$(df -h / | awk '/^\// {print $3 "/" $2 " (" $5 ")"}')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
lIP="$(hostname -I | awk '{print $1}')"
# pIP="$(curl -s http://ipecho.net/plain)"

echo '          _,met$$$$$gg.        User:' $User
echo '       ,g$$$$$$$$$$$$$$$P.     OS:' $OS
echo '     ,g$$P""       """Y$$.".   Desktop:' $Desktop
echo '    ,$$P"              `$$$."  Kernel:' $Kernel
echo '   ,$$P       ,ggs.     `$$b:  Uptime:' $Uptime
echo '  `d$$"     ,$P""   .    $$$   Packages:' $Pack_dpkg \(dpkg\), $Pack_flat \(flatpak\)
echo '   $$P      d$"     ,    $$P   CPU:' $CPU
echo '   $$:      $$.   -    ,d$$"   GPU:' $GPU
echo '   $$\;      Y$b._   _,d$P     Disk (\):' $Disk
echo '   Y$$.    `.`"Y$$$$P""        RAM:' $RAM
echo '   `$$b      "-.__             Local IP:'  $lIP
echo '    `Y$$                       ' # Public IP:' $pIP
echo '     `Y$$.                     '
echo '       `$$b.                   '
echo '         `Y$$b.                '
echo '            `"Y$b._            '
echo '                `""""          '
